# Bun CI Workflow Template
# Copy to .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '24'

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.1.42'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: bun run build.js

      - name: Test
        run: npm test

      - name: Lint
        run: npm run lint
